language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
  - Pharo-6.0
#  - Moose-trunk
#  - Moose-6.1
#

smalltalk_config:
  - .smalltalk.ston
  - .headless.ston

matrix:
  include:
    - smalltalk: Pharo-stable
      smalltalk_config: .smalltalk.ston
  include:
    - smalltalk: Pharo-stable
      smalltalk_config: .headless.ston
  allow_failures:
   - smalltalk: Pharo-alpha
